name: docker-build
on:
  push:
    branches:
      - main

env:
  PR_ID: ${{ github.event.pull_request.number || 'main' }}

concurrency:
  group: docker-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: 'scaleway/scaleway-cli'
      - name: setup_buildx
        uses: docker/setup-buildx-action@v1
      - name: login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker-build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }},ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max